name: Python package

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.7] # [3.6, 3.7, 3.8] # 3.9]
        platform: [ubuntu-latest] #, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry export --without-hashes -f requirements.txt > requirements.txt
        poetry export --dev --without-hashes -f requirements.txt > requirements-dev.txt
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{ (matrix.platform == 'ubuntu-latest') && (matrix.python-version == 3.7) }}
      with:
        commit_message: "fix: update requirements.txt"
        push_options: --force
        file_pattern: requirements*.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are linting errors accoring to `.flake8`
        poetry run flake8 . --count --show-source --statistics
    - name: Test with pytest
      run: |
        # Ignore test_being_robust_compare_with_matlab.py due to `np.load` problems
        poetry run pytest tests/ --doctest-modules --junitxml=junit/test-results.xml --cov=being_robust --cov-report=xml --cov-report=html --ignore=tests/test_being_robust_compare_with_matlab.py
